apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup

spec:
  workspace:
  - name: source
  workingDir: "$(workspace.source.path)"
  steps:
  - name: remove
    image: alpine:3
    env:
      name: WORKSPACE_SOURCE_PATH
      value: "$(workspace.source.path)"
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    script: |
      #!/bin/bash

      set --eu

      if [-d "${WORKSPACE_SOURCE_PATH}"]; then

      rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*

      rm -rf "${WORKSPACE_SOURCE_PATH}"/.[.!]*

      rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*

      fi

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose

spec:
  workspace:
  - name: source

  params:
  - name: args
    description: arguments to pass to nose
    type: string
    default: "-v"
  
  steps:
  - name: nosetests
    image: python:3.9-slim
    script: |
      #!/bin/bash
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      nosetests "$(params.args)"
  workingDir: "$(workspace.source.path)"

  

