name: CI workflow

on:
  push:
    branches:
    - 'main'
  pull_request:
    - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          python -m pip install --upragde pip
          pip install -r requirements.txt
      
